### ISSUE TITLE
No such file or directory (Proxypass-pakkit.jar)

### ISSUE THREAD

**Issue by Tacoalarmclock** [Heath123/pakkit#13]
![Screenshot 2021-01-17 at 8 31 34 AM](https://user-images.githubusercontent.com/45108867/104849430-6f480500-589e-11eb-9ace-f298fbc04d60.png)

This file was not included in the macOS download.

**Comment by Tacoalarmclock** [comment]
For your reference, here is the file https://github.com/Heath123/pakkit/blob/master/data/proxypass-pakkit.jar

![Screenshot 2021-01-17 at 8 36 49 AM](https://user-images.githubusercontent.com/45108867/104849551-22186300-589f-11eb-81f2-59893d13152c.png)
These were the only files that were in the zip.

**Comment by Heath123** [comment]
Hmm, probably a Jenkinsfile problem. I'll fix it soon hopefully. I haven't actually tested it on Mac OS because I don't have a Mac.

**Comment by Tacoalarmclock** [comment]
Indeed it likely is. A manual installation worked perfectly!

**Comment by Tacoalarmclock** [comment]
... Is what I thought. It may have to do with my server being on localhost, but I'm not seeing any of the expected packets show up. At all.

**Comment by Heath123** [comment]
> 
> 
> ... Is what I thought. It included all the files and the electron app started, but then no packets were showing up, even when they should have, such as block place/break, walk, fly, etc.

@Tacoalarmclock 
Are you trying to connect directly to the server? If you are you need to connect to pakkit (it's a proxy, not a sniffer)

**Comment by Tacoalarmclock** [comment]
ohhh. I think that was it.

**Comment by Kas-tle** [comment]
I believe #20 should resolve this
