### ISSUE TITLE
Unable to login to premium servers.

### ISSUE THREAD

**Issue by xXNurioXx** [Heath123/pakkit#14]
I'm not able to use Pakkit with premium servers.
I have granted the checkbox to read my `.minecraft` data and it doesn't require me ever again.

The error I got in the spigot server is: `lost connection: Failed to verify username!`
And in the client side is: `Connection closed by server`

**Fact:** I have more than one logged-in accounts on my `profile.json`, so, the problem may come from there.

**Comment by Heath123** [comment]
If you have a new launcher version it might be because they moved credentials to launcher_accounts.json, does that file exist for you?

**Comment by xXNurioXx** [comment]
```
ls -la | grep .json
``` 
```
-rw-r--r-- 1 Nurio 197121   1007 Jan 24 10:59 launcher_accounts.json
-rw-r--r-- 1 Nurio 197121    386 Jan 24 10:19 launcher_msa_credentials.json
-rw-r--r-- 1 Nurio 197121   4763 Jan 24 11:00 launcher_profiles.json
-rw-r--r-- 1 Nurio 197121    221 Jan 24 10:19 launcher_settings.json
-rw-r--r-- 1 Nurio 197121    524 Jan 23 08:25 launcher_ui_state.json
-rw-r--r-- 1 Nurio 197121    131 Jan  1 01:41 realms_persistence.json
-rw-r--r-- 1 Nurio 197121    108 Jan 24 10:56 usercache.json
```

**Comment by Heath123** [comment]
Yes, OK, that's the problem then

**Comment by Heath123** [comment]
I'll try to fix this soon

**Comment by Xstoudi** [comment]
Is it fixed yet?

**Comment by YHDiamond** [comment]
Not yet, but its in the works

**Comment by YHDiamond** [comment]
This PR will be closed when its fixed.

**Comment by Heath123** [comment]
Do you mean issue?

**Comment by YHDiamond** [comment]
Yes I do

**Comment by Moondarker** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/pull/826 upstream should fix it if it gets merged
