### ISSUE TITLE
consider using github action instead of jenkins 

### ISSUE THREAD

**Issue by rom1504** [Heath123/pakkit#18]
it's so much better

**Comment by rtm516** [comment]
Can you provide reasons? Seems like alot of hassle to migrate over to actions yml files when the current system does work. Ultimately its up to circuit.

**Comment by rom1504** [comment]
does it work https://ci.rtm516.co.uk/job/pakkit/job/master/83/ ?

**Comment by rtm516** [comment]
> does it work https://ci.rtm516.co.uk/job/pakkit/job/master/83/ ?

Yes. Just triggered a rebuild and it has no issues.

**Comment by rom1504** [comment]
ok then, if you like jenkins then good
