### ISSUE TITLE
Error with regex parsing

### ISSUE THREAD

**Issue by u9g** [Heath123/pakkit#22]
When regex parsing is enabled the regex `entity_` matches all packets starting with "entity_", but the regex `(entity_)` just doesn't match anything?

**Comment by Heath123** [comment]
Isn't that a capturing group?

**Comment by u9g** [comment]
> Isn't that a capturing group?

yes but it should still work, no?

**Comment by Heath123** [comment]
I think this is fixed in the latest commit, reopen it if not
