### ISSUE TITLE
Bedrock outdated client

### ISSUE THREAD

**Issue by KosmX** [Heath123/pakkit#24]
I can't connect to a BEDROCK server with pakkit. The client tells me that I'm using an outdated client.

I can connect to the same server with the same client without pakkit.
using BE `1.16.220`

**Comment by Heath123** [comment]
I might have an old ProxyPass version, I can try updating it

**Comment by KosmX** [comment]
So I could not wait any longer...
#29 
I also did a PR to your ProxyPass fork

**Comment by Heath123** [comment]
Sorry, I my=ust have forgotten about this
