### ISSUE TITLE
[MacOS] Proxy Sub-Process Is Not Killed on Quit

### ISSUE THREAD

**Issue by Kas-tle** [Heath123/pakkit#26]
### Description
On MacOS, the sub-process initiated by the proxy is not killed on application quit. This seems to cause starting a Bedrock proxy to fail if the same port is used, provided one does not first manually kill the sub-process for the previous proxy. The failure is caused because the previous sub-process is using the port, leading to the new sub-process being unable to bind to the given port. I believe this does not occur for Java proxies since no sub-process seems to be created.

### Reproduction
1. Open the Pakkit executable from Terminal
2. Start a Bedrock proxy on some port and observe that the proxy starts
3. Quit Pakkit
4. Open Activity Monitor
5. Search for Java processes and confirm there is a Java process still running
6. Reopen Pakkit
7. Start a Bedrock proxy on the same port previously used
8. Observe that the proxy fails to bind as the port is already in use
9. Observe that there are now two Java processes in Activity Monitor
10. Quit Pakkit
11. Force quit the Java process in Activity Monitor
12. Reopen Pakkit
13. Start another Bedrock proxy on the same port
14. Observe the proxy again successfully binds with the Java processes killed

### System Information
MacBook Pro (Retina, 15-inch, Mid 2015)
MacOS Mojave 10.14.6 (18G8022)

### Video

https://user-images.githubusercontent.com/26531652/115824530-e79df500-a3bc-11eb-9f7f-e85d3e00c315.mp4

**Comment by Heath123** [comment]
Should be fixed now
