### ISSUE TITLE
Why it don't work?

### ISSUE THREAD

**Issue by pthon5** [Heath123/pakkit#3]
Hi, i just select game version and paste server IP, but i get error every time
![image](https://user-images.githubusercontent.com/53282687/88385975-de99dc00-cdc8-11ea-800f-39510b5c582b.png)

**Comment by Heath123** [comment]
You're already running a server or another instance of pakkit on port 25566, try using another port.

**Comment by pthon5** [comment]
> You're already running a server or another instance of pakkit on port 25566, try using another port.

Thanks, it helps me.
Write pls instruction for use this app for other users)

**Comment by Heath123** [comment]
I'll probably make the error messages a bit clearer soon
