### ISSUE TITLE
I CANT CONNECT TO SERVER

### ISSUE THREAD

**Issue by guimc233** [Heath123/pakkit#34]
![image](https://user-images.githubusercontent.com/65482560/127350297-da2f4013-5d54-4b2f-93ae-1c0b4014935e.png)
MCVersion:1.8.x
System:Windows 11 x64

**Comment by Heath123** [comment]
What settings are you using? Are you connecting to pakkit or directly to the server? (you need to connect to pakkit on localhost)

**Comment by liulihaocai** [comment]
redesky have a SRV record
but idk pakkit have the SRV connectbility

**Comment by guimc233** [comment]
> What settings are you using? Are you connecting to pakkit or directly to the server? (you need to connect to pakkit on localhost)

I‘m connect to localhost

**Comment by guimc233** [comment]
> redesky have a SRV record
> but idk pakkit have the SRV connectbility

How can i get the real address?

**Comment by guimc233** [comment]
> redesky have a SRV record
> but idk pakkit have the SRV connectbility

OK,but how can I solve this problem?

**Comment by duoduo2333** [comment]
> > redesky have a SRV record
> > but idk pakkit have the SRV connectbility
> 
> OK,but how can I solve this problem?

try to connect rsgg3rmpk7tz362p.ddns.net:25565(the srv record of _minecraft._tcp.redesky.gg)

**Comment by guimc233** [comment]
> > > redesky have a SRV record
> > > but idk pakkit have the SRV connectbility
> > 
> > 
> > OK,but how can I solve this problem?
> 
> try to connect rsgg3rmpk7tz362p.ddns.net:25565(the srv record of _minecraft._tcp.redesky.gg)

Okkkkkk,thanks! I'll try!

**Comment by Heath123** [comment]
I’ll check if SRV works properly at some point
