### ISSUE TITLE
Packet parsing problem

### ISSUE THREAD

**Issue by dianwangwin** [Heath123/pakkit#51]
Like he will put the Integer.MIN_VALUE to 0 (like ConfirmTransaction) one

**Comment by Heath123** [comment]
Is this on Bedrock Edition?

**Comment by dianwangwin** [comment]
nah Minecraft 1.8.9

**Comment by Heath123** [comment]
Is this the packet with the problem? https://wiki.vg/index.php?title=Protocol&oldid=7368#Confirm_Transaction

So you mean a value that should be -2147483648 is changed to 0?

**Comment by dianwangwin** [comment]
yes (windows id one)
