### ISSUE TITLE
Falsely claiming online mode

### ISSUE THREAD

**Issue by timvandam** [Heath123/pakkit#55]
Title. I am using pakkit on a custom server that uses compression. It does not use encryption so I don't know why it thinks it uses online mode

![image](https://user-images.githubusercontent.com/35376389/153302722-0529f9b8-a15a-401f-9367-878b2354524a.png)

In the image you can see that packets are correctly intercepted in the background

**Comment by Heath123** [comment]
Is there a way that I can reproduce this?

**Comment by timvandam** [comment]
Ah I guess it's either `minecraft-protocol` or my own server then. It happens when I use pakkit with my own server: https://github.com/timvandam/minecraft-server

**Comment by Heath123** [comment]
Should be fixed now, tell me if you're still getting this
