### ISSUE TITLE
Not logging handshake and login start packets

### ISSUE THREAD

**Issue by ninjadev64** [Heath123/pakkit#65]
Not much else to say, it isn't logging handshake and login start packets sent to the server, my custom server detects and logs them so they are being sent through

**Comment by Heath123** [comment]
Someone requested this before I think, but I can't find it. Anyway, the library I'm using abstracts this away, but I can probably find a way to make it report the login packets if you need this

**Comment by ninjadev64** [comment]
The second bit about malformed packets is much more important (I'm good with the handshake and login, just was wondering why it didn't log them)

**Comment by Heath123** [comment]
> That would be great, thanks - also could you make it log malformed packets? I'm writing a server and I'm trying to use this to see what I'm doing wrong with my status response packet.

I think I implemented some level of basic support for this, but I'll need to make sure it works fully. Malformed packets will have to only be visible as hex, of course, because they can't be decoded

**Comment by ninjadev64** [comment]
I think this was resolved a while ago, thanks
