### ISSUE TITLE
New electron won't load hex-viewer

### ISSUE THREAD

**Issue by YveIce** [Heath123/pakkit#69]
CORS-Error because of iframing local resource. 
Best solution would be, to add the DOM content to startPage/index.html and put all inline-scripts in extra js-files.

**Comment by Heath123** [comment]
Are you sure it's a CORS error? It looks like I'm just not cloning the submodules in the build process, since the files are entirely missing

**Comment by YveIce** [comment]
Sure it was. I dumped my self the hexviewer part, so files was there. 
But with the latest release 83, seems fixed. So can be closed.
