### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by Peter-Crawley** [Heath123/pakkit#70]

**Comment by Heath123** [comment]
It doesn't seem to be supported in https://github.com/PrismarineJS/node-minecraft-protocol yet so I need to wait for that

**Comment by NoahvdAa** [comment]
Looks like [1.19.0 is now supported](https://github.com/PrismarineJS/node-minecraft-protocol/commit/d7c5053a13efec714bad1acb8d00b5a700cbb345), with .1/.2 still todo.

**Comment by Heath123** [comment]
I added it, but it's not tested yet
