### ISSUE TITLE
How its works?

### ISSUE THREAD

**Issue by ITEXNIKJS** [Heath123/pakkit#71]
I enter the address and port of the server, then I log on to it, but nothing happens.

Windows 10 20H2
pakkit v69, 71, 73

**Comment by YveIce** [comment]
Did you:
1.) Select the correct Plattform (Java/Badrock)?
2.) Select the correct Version of your Client?
3.) Set in the field "Connect address" the ip or url to the running minecraft server?
4.) Set in Connect port, the correct port the minecraft instance is running on the server? (Some server use non default ports via SRV-Lookup, Pakkit can't look up them currently, you have to find out it by your own)
5.) Set in the field "Listen port:" a Port number of your system that is unused and not blocked by any other software/firewall? (Maybe try different port like 6666)
6.) In your minecraft client, did you set "localhost:6666" (localhost + ":" + Listen Port you selected) as Server-Adresse? 
7.) Do you now exactly what a proxy is?

If you can answer all with yes, then please explain more what "nothing happens" means to you.

**Comment by ITEXNIKJS** [comment]
I miss stage 6)
