### ISSUE TITLE
add 1.19.2 support

### ISSUE THREAD

**Issue by Hunam6** [Heath123/pakkit#82]
Could you add 1.19.2 support?

**Comment by Heath123** [comment]
Currently blocked by https://github.com/PrismarineJS/node-minecraft-protocol/issues/1037 but when that's done it shouldn't be too hard

**Comment by MelonHell** [comment]
> Currently blocked by [PrismarineJS/node-minecraft-protocol#1037](https://github.com/PrismarineJS/node-minecraft-protocol/issues/1037) but when that's done it shouldn't be too hard

seems to have been added

**Comment by MelonHell** [comment]
> Currently blocked by [PrismarineJS/node-minecraft-protocol#1037](https://github.com/PrismarineJS/node-minecraft-protocol/issues/1037) but when that's done it shouldn't be too hard

seems to have been added

**Comment by Heath123** [comment]
> > Currently blocked by [PrismarineJS/node-minecraft-protocol#1037](https://github.com/PrismarineJS/node-minecraft-protocol/issues/1037) but when that's done it shouldn't be too hard
> 
> seems to have been added

Thanks for telling me, I will add it soon (hopefully)
