### ISSUE TITLE
Proxy won't start

### ISSUE THREAD

**Issue by ethrx** [Heath123/pakkit#92]
Have tried building from source, as well as release latest and release 86 - still get the same error every time.
![image](https://user-images.githubusercontent.com/70865398/228586974-00f6e0c2-a32d-45fd-a4ac-5aca3a69480d.png)
Not sure why it's doing this...

**Comment by ethrx** [comment]
Sorry I believe I misunderstood. There is no error here.

**Comment by Heath123** [comment]
Yes, this shows up and I'm not sure why but it seems to work anyway, I should still fix that though
