### ISSUE TITLE
Pakkit doesn't seem to detect MS finished (online-mode)

### ISSUE THREAD

**Issue by Hunam6** [Heath123/pakkit#93]
When online-mode is enabled, Pakkit asks me to login with a code:
<img width="531" alt="Screenshot 2023-04-15 at 17 38 23" src="https://user-images.githubusercontent.com/38606542/232230974-6ffe9135-de15-478f-b8dc-291d0631363d.png">
I do it, then it redirects me to this page https://account.microsoft.com/?lang=en-US&refd=account.live.com&refp=landing&mkt=EN-US
<img width="1237" alt="Screenshot 2023-04-15 at 17 39 44" src="https://user-images.githubusercontent.com/38606542/232231080-87c8e4e6-ca98-417b-a85e-0a3a3a9a4b34.png">

**But the login screen of Pakkit doesn't go away.**

**Comment by Heath123** [comment]
That’s strange, it should ask you to put in a code at least

**Comment by YveIce** [comment]
Can u try two things:
- first: open an private-tab, then enter url: "https://microsoft.com/link" and check if it works
- second: open "https://login.live.com/oauth20_remoteconnect.srf" (thats the url it should redirect) in the normal Browser, check if it's redirects you too, to something different. 

The page should look like that: 
![image](https://user-images.githubusercontent.com/42624289/232249673-a245c0bc-9778-4c38-9612-aa6b4d8af8e5.png)

**Comment by Hunam6** [comment]
> That’s strange, it should ask you to put in a code at least

Sorry, I guess I wasn't clear, when I said "I do it" I meant, typing the code, and pressing next, getting this:
<img width="533" alt="Screenshot 2023-04-16 at 01 52 51" src="https://user-images.githubusercontent.com/38606542/232256446-125831d2-cb42-4f43-833d-6510762c64c7.png">
pressing next and then I get redirected to the MS account home page and the Pakkit app login screen doesn't go away.

**Comment by Hunam6** [comment]
@YveIce

1st: works
2nd: I click on the link, then enter the code, click next, click next, redirected to MS account home page and the Pakkit app login screen doesn't go away.

**Comment by Hunam6** [comment]
Found the solution with the help of @adepierre, if anyone have this issue, it's because you're logging in using your Github account, in the login process you must click on "Other ways to sign in" then "Use my password".
<img width="533" alt="Screenshot 2023-04-16 at 01 52 51" src="https://user-images.githubusercontent.com/38606542/232323198-86cc8b5f-2a46-4f55-8bd6-3fac0ae9ba37.png">
